<<<<<<< HEAD
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

=======
>>>>>>> 35be87f (renamed)
name: Python application

on:
  push:
<<<<<<< HEAD
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
=======
    branches: [ "development", "production" ]
  pull_request:
    branches: [ "development", "production" ]
>>>>>>> 35be87f (renamed)

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

<<<<<<< HEAD
=======
    # specify the environment in which the job is running
    environment: 
      name: default

>>>>>>> 35be87f (renamed)
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
<<<<<<< HEAD
=======
      env:
        # use the secret from the environment
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production' || github.ref == 'refs/heads/development'

    steps:
    - name: Deploy to Production
      if: github.ref == 'refs/heads/production'
      run: |
        echo "Deploying to Production"
        python -m pip install --upgrade setuptools wheel twine
        python setup.py sdist bdist_wheel
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ env.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        

    - name: Deploy to Development
      if: github.ref == 'refs/heads/development'
      run: |
        echo "No deployment for Development"
>>>>>>> 35be87f (renamed)
